name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # cambia si quieres otra branch
      - fly-deployment  # branch alternativa para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --app iic3964-backend --org personal
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
